# Generated by Django 4.1.2 on 2022-10-24 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_description', models.TextField()),
                ('cat_pub_date', models.DateTimeField(verbose_name='date_published')),
                ('cat_upd_date', models.DateTimeField(verbose_name='date_updated')),
            ],
        ),
        migrations.CreateModel(
            name='Users_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_name', models.CharField(max_length=20)),
                ('us_email', models.EmailField(max_length=200)),
                ('us_master_password', models.CharField(max_length=64)),
                ('us_mp_hint', models.CharField(max_length=200, null=True)),
                ('us_pub_date', models.DateTimeField(verbose_name='date_published')),
                ('us_upd_date', models.DateTimeField(verbose_name='date_updated')),
            ],
        ),
        migrations.CreateModel(
            name='ItemWebPage_iwp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iwp_name', models.CharField(max_length=50)),
                ('iwp_url', models.URLField()),
                ('iwp_username', models.CharField(max_length=20)),
                ('iwp_password', models.CharField(max_length=64)),
                ('iwp_description', models.TextField()),
                ('iwp_pub_date', models.DateTimeField(verbose_name='date_published')),
                ('iwp_upd_date', models.DateTimeField(verbose_name='date_updated')),
                ('principal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmb_base.users_us')),
                ('user_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmb_base.category_cat')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPaymentCard_ipc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipc_name', models.CharField(max_length=50)),
                ('ipc_company', models.CharField(max_length=30)),
                ('ipc_card_number', models.CharField(max_length=20)),
                ('ipc_card_pin', models.IntegerField()),
                ('ipc_card_strt_date', models.DateField()),
                ('ipc_card_exp_date', models.DateField()),
                ('ipc_card_description', models.TextField()),
                ('ipc_pub_date', models.DateTimeField(verbose_name='date_published')),
                ('ipc_upd_date', models.DateTimeField(verbose_name='date_updated')),
                ('principal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmb_base.users_us')),
            ],
        ),
        migrations.AddField(
            model_name='category_cat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmb_base.users_us'),
        ),
    ]
